services:
    _defaults:
        autoconfigure: true
        autowire: true

    EonX\EasySsm\Services\Dotenv\EnvLoaderInterface:
        class: EonX\EasySsm\Services\Dotenv\Loaders\ConsoleOutputLoader
