services:
    _defaults:
        autoconfigure: true
        autowire: true

    EonX\EasySsm\:
        resource: '../src'
        exclude:
            - '../src/HttpKernel/*'
            - '../src/Services/Aws/Data/*'
            - '../src/Services/Dotenv/Data/*'
            - '../src/Services/Dotenv/Loaders/*'
            - '../src/Services/Parameters/Data/*'

    EonX\EasySsm\Services\Dotenv\SsmDotenvInterface:
        class: EonX\EasySsm\Services\Dotenv\SsmDotenv
        public: true

    Symfony\Component\Console\Output\OutputInterface:
        class: Symfony\Component\Console\Output\ConsoleOutput

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
